import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="scroll-smooth" lang="FA">
      <body dir="rtl" className={`antialiased font-[dana] overflow-x-hidden max-w-full bg-[#111827] text-white scroll-smooth text-transparent`}>
        {children}
      </body>
    </html>
  );
}